{% set name = "conda-index" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0d83fd01af3c5b17860a86c1e217090a19b6e262114a242bc7f4ff212ed1e705

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - flit-core
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8
    - conda >=4.12.0
    - conda-package-streaming
    - filelock
    - jinja2
    - more-itertools
    - PyYAML >=6

test:
  requires:
    - conda-build >=3.21.0
    - conda-package-handling >=1.9.0
    - coverage
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
    - toolz
  commands:
    - pytest -k test_index_on_single_subdir_1
  imports:
    - conda_index.index
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - mbargull
    - AndresGuzman-Ballen
    - dholth
    - jharlow-intel
