{% set name = "conda-index" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 12d78ec6dc55f64ad68761108a416ebde3dc6472f257045ddfa45378980c9074

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 1
  noarch: python

requirements:
  host:
    - flit-core
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click >=8
    - conda >=4.12.0
    - conda-package-streaming
    - filelock
    - jinja2
    - more-itertools
    - PyYAML >=6

test:
  requires:
    - conda-build >=3.21.0
    - conda-package-handling >=1.9.0
    - coverage
    - fsspec
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
    - toolz
    - python {{ python_min }}
  commands:
    - pytest -k test_index_on_single_subdir_1
  imports:
    - conda_index.index
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - kenodegard
    - AndresGuzman-Ballen
    - dholth
    - jharlow-intel
