{% set name = "conda-index" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: afbf3850b2197ab4ceb7785bee462e063bd498488c185112477cbe4197e70aad

build:
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click >=8
    - conda >=4.14.0
    - conda-package-streaming >=0.7.0
    - filelock
    - jinja2
    - msgpack-python >=1.0.2
    - ruamel.yaml
    - zstandard

test:
  requires:
    - conda-build >=24
    - conda-package-handling >=2.2.0
    - coverage
    - fsspec
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
    - python {{ python_min }}
  commands:
    - pytest -k test_index_on_single_subdir_1
  imports:
    - conda_index.index
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - kenodegard
    - AndresGuzman-Ballen
    - dholth
    - jharlow-intel
