{% set name = "conda-index" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 93034029c5d3b13ba4837d0b7813206c2faedf0a46bf25952d4d8a3882e31206

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - flit-core
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click >=8
    - conda >=4.14.0
    - conda-package-streaming
    - filelock
    - jinja2
    - more-itertools
    - msgpack-python >=1.0.2
    - ruamel.yaml

test:
  requires:
    - conda-build >=24
    - conda-package-handling >=2.2.0
    - coverage
    - fsspec
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
    - python {{ python_min }}
  commands:
    - pytest -k test_index_on_single_subdir_1
  imports:
    - conda_index.index
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - kenodegard
    - AndresGuzman-Ballen
    - dholth
    - jharlow-intel
